import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ChatBox from '@/app/components/ChatBox'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ height: "100%" }}>
      <head>

        <meta name="viewport" content="width=device-width, initial-scale=1.0, interactive-widget=resizes-content" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <body style={{ background: 'white', overflow: 'hidden', height: "100vh" }} className={inter.className}>

        <div><ChatBox /></div>{children}
        
        
        <script>
          
        </script>
        </body>
    </html>
  );
}
